create database mobile;
use  mobile;
create table custumer_info(customer_id varchar(10) primary key,
customer_name varchar(20) not null,address varchar(100),
mobile bigint not null,email varchar(30));
create table distributer(distributer_id varchar(10) primary key,distributer_name varchar(20) not null,
address varchar(100) not null,mobile bigint not null,email varchar(30));
create table mobile_master(IME_NO VARCHAR(10) primary KEY,MODEL_NAME VARCHAR(20) NOT NULL,
MANUFACTURE VARCHAR(20) NOT NULL,DATE_OF_MANUFAC DATE,WARRENTY_IN_YEARS INT,PRICE DECIMAL(7,2),
DISTRIBUTER_ID VARCHAR(10), foreign key(DISTRIBUTER_ID) REFERENCES DISTRIBUTER(DISTRIBUTER_ID));
DESC MOBILE_MASTER;
CREATE TABLE MOBILE_SPECIFICATION(IME_NO VARCHAR(10),
DIMENSION VARCHAR(10),WEIGHT VARCHAR(10),DISPLAY_TYPE VARCHAR(10),DISPLAY_SIZE VARCHAR(10),INTERNAL_MEM_IN_MB INT,
MEMORY_CARD_CAPACITY_GB INT,NETWORK VARCHAR(10),GPRS VARCHAR(10),CAMERA VARCHAR(10),OS VARCHAR(10),
foreign key(IME_NO) REFERENCES MOBILE_MASTER(IME_NO));
CREATE TABLE SALES_INFO(SALES_ID INT PRIMARY KEY,SALES_DATE DATE,IME_NO VARCHAR(10),
foreign key(IME_NO) REFERENCES MOBILE_MASTER(IME_NO),PRICE INT,DISCOUNT INT,NET_AMOUNT INT,MODEL_NAME VARCHAR(20),
CUSTOMER_ID VARCHAR(10),foreign key(CUSTOMER_ID) references CUSTUMER_INFO(CUSTOMER_ID));
